routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Route;

//Route::get('/', function () {
//
//    Route::name('dashboard.')->prefix('/panel')->group(function (){
//
//        Route::name('users.')->prefix('/uzytkownicy')->group(function (){
//            Route::get('/', 'Dashboard\UserController@index')->name('index');
//            Route::get('/create', 'Dashboard\UserController@create')->name('create');
//            Route::post('/create', 'Dashboard\UserController@store')->name('store');
//            Route::get('/{user_id}', 'Dashboard\UserController@edit')->name('edit');
//            Route::put('/{user_id}', 'Dashboard\UserController@update')->name('update');
//            Route::delete('/{user_id}', 'Dashboard\UserController@destroy')->name('delete');
//        });
//
//        Route::name('locals.types.')->prefix('/typy-lokali')->group(function (){
//            Route::get('/', 'Dashboard\LocalTypeController@index')->name('index');
//            Route::get('/create', 'Dashboard\LocalTypeController@create')->name('create');
//            Route::post('/create', 'Dashboard\LocalTypeController@store')->name('store');
//            Route::get('/{type_id}', 'Dashboard\LocalTypeController@edit')->name('edit');
//            Route::put('/{type_id}', 'Dashboard\LocalTypeController@update')->name('update');
//            Route::delete('/{type_id}', 'Dashboard\LocalTypeController@destroy')->name('delete');
//        });
//
//        Route::name('locals.')->prefix('/lokale')->group(function (){
//            Route::get('/', 'Dashboard\LocalController@index')->name('index');
//            Route::get('/create', 'Dashboard\LocalController@create')->name('create');
//            Route::post('/create', 'Dashboard\LocalController@store')->name('store');
//            Route::get('/edit/{premise_id}', 'Dashboard\LocalController@edit')->name('edit');
//            Route::put('/edit/{premise_id}', 'Dashboard\LocalController@update')->name('update');
//            Route::delete('/{premise_id}', 'Dashboard\LocalController@destroy')->name('delete');
//        });
//    });
//
//
//});

app/Models/LocalStats.php
<?php
/**
 * Created by PhpStorm.
 * User: Marcin-Komputer
 * Date: 31.03.2020
 * Time: 00:23
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class LocalStats extends Model
{
    use SoftDeletes;

    protected $table = 'locals_stats';

    protected $fillable = [
        'local_id',
        'rating',
        'count_rating',
        'count_comments',
        'count_followers',
        'count_images'
    ];

    public function local()
    {
        return $this->hasOne(Local::class, 'local_stats_id');
    }

    public function getCreatedAtAttribute($value):Carbon
    {
        return Carbon::parse($value);
    }

    public function getUpdatedAtAttribute($value):Carbon
    {
        return Carbon::parse($value);
    }

    public function getDeletedAtAttribute($value):?Carbon
    {
        IF($value)
            return Carbon::parse($value);

        return NULL;
    }
}

app/Http/Controllers/Dashboard/LocalController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Forms\Dashboard\LocalCreateForm;
use App\Forms\Dashboard\LocalIndexSearchForm;
use App\Models\AclUserGroup;
use App\Repositories\Filters\Dashboard\LocalIndexFilter;
use App\Repositories\LocalRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class LocalController extends Controller
{
    use FormBuilderTrait;

    protected $localRepository;

    public function __construct(
        LocalRepository $localRepository
    )
    {
        $this->localRepository = $localRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param LocalIndexFilter $filter
     * @return \Illuminate\Http\Response
     */
    public function index(LocalIndexFilter $filter)
    {
        if(Auth::user()->acl_group->slug == AclUserGroup::ADMIN_SLUG)
            $locals = $this->localRepository->paginate($filter);
        else
            $locals = $this->localRepository->paginateForOwner(Auth::user(), $filter);

        $formSearch = $this->form(LocalIndexSearchForm::class,[
            'model' => $filter->getFilterValues()
        ]);

        return view('dashboard.locals.index', compact('locals', 'formSearch'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $local = $this->localRepository->findOrNew();

        $form = $this->form(LocalCreateForm::class, [
            'model' => $local,
            'method' => 'POST',
            'url' => route('dashboard.locals.store')
        ]);

        return view('dashboard.locals.create', compact('local','form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        $local = $this->localRepository->findOrNew();

        $form = $this->form(LocalCreateForm::class, [
            'model' => $local,
        ]);

        if(!$form->isValid())
            return redirect()->back()->withInput()->withErrors($form->getErrors())->with('error', trans('messages.locals.store.error'));

        $this->localRepository->updateByData($local,$form->getFieldValues());

        $this->localRepository->store($local);

        if(Auth::user()->acl_group->slug == AclUserGroup::ADMIN_SLUG)
            $local->local_owners()->attach($form->getFieldValues()['owners_id']);
        else
            $local->local_owners()->attach(Auth::user()->id);

        return redirect()->route('dashboard.locals.index')->with('success', trans('messages.locals.store.success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $local = $this->localRepository->findOrFail($id);

        return view('dashboard.locals.show', compact('local'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $local = $this->localRepository->findOrFail($id);

        $form = $this->form(LocalCreateForm::class, [
            'model' => $local,
            'method' => 'POST',
            'url' => route('dashboard.locals.edit', ['id' => $local->id])
        ]);

        return view('dashboard.locals.edit', compact('local', 'form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $local = $this->localRepository->findOrFail($id);

        $form = $this->form(LocalCreateForm::class, [
            'model' => $local,
        ]);

        if(!$form->isValid())
            return redirect()->back()->withInput()->withErrors($form->getErrors())->with('error', trans('messages.locals.store.error'));

        $formData = $form->getFieldValues();

        $this->localRepository->updateByData($local,$formData);

        $this->localRepository->store($local);

        if(Auth::user()->acl_group->slug == AclUserGroup::ADMIN_SLUG)
            $local->local_owners()->sync($formData['owners_id']);

        return redirect()->route('dashboard.locals.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $local = $this->localRepository->findOrFail($id);

        return redirect()->route('dashboard.locals.index');
    }
}

app/Http/Controllers/Front/EventController.php
<?php
/**
 * Created by PhpStorm.
 * User: Marcin-Komputer
 * Date: 28.11.2019
 * Time: 18:55
 */

namespace App\Http\Controllers\Front;


use App\Forms\Front\EventIndexSearchForm;
use App\Http\Controllers\Controller;
use App\Repositories\EventRepository;
use App\Repositories\Filters\Front\EventIndexFilter;
use App\Repositories\LocalRatingRepository;
use App\Repositories\LocalRepository;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class EventController extends Controller
{
    use FormBuilderTrait;

    protected $eventRepository;
    protected $localRepository;
    protected $localRatingRepository;

    public function __construct(
        EventRepository $eventRepository,
        LocalRepository $localRepository,
        LocalRatingRepository $localRatingRepository
    )
    {
        $this->eventRepository = $eventRepository;
        $this->localRepository = $localRepository;
        $this->localRatingRepository = $localRatingRepository;

    }

    public function index(EventIndexFilter $eventIndexFilter)
    {
        $events = $this->eventRepository->paginate($eventIndexFilter);

        $formSearch = $this->form(EventIndexSearchForm::class, ['model' => $eventIndexFilter->getFilterValues()]);

        return view('front.events.index', compact('events', 'formSearch'));
    }

    public function show(int $id)
    {
        $event = $this->eventRepository->findOrFail($id);

        $ratings = $this->localRatingRepository->paginateForLocal($event->local);

        return view('front.events.show', compact('event','ratings'));
    }
}

app/Http/Controllers/Front/HomeController.php
<?php
/**
 * Created by PhpStorm.
 * User: Marcin-Komputer
 * Date: 28.11.2019
 * Time: 19:19
 */

namespace App\Http\Controllers\Front;


use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        return view('front.home.index');
    }
}

app/Http/Controllers/Front/LocalController.php
<?php
/**
 * Created by PhpStorm.
 * User: Marcin-Komputer
 * Date: 28.11.2019
 * Time: 18:55
 */

namespace App\Http\Controllers\Front;


use App\Forms\Front\LocalIndexSearchForm;
use App\Forms\Front\LocalRatingShowSearchForm;
use App\Http\Controllers\Controller;
use App\Repositories\Filters\Front\LocalIndexFilter;
use App\Repositories\Filters\Front\LocalRatingShowFilter;
use App\Repositories\LocalRatingRepository;
use App\Repositories\LocalRepository;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class LocalController extends Controller
{
    use FormBuilderTrait;

    protected $localRepository;
    protected $localRatingRepository;

    public function __construct(
        LocalRepository $localRepository,
        LocalRatingRepository $localRatingRepository
    )
    {
        $this->localRepository = $localRepository;
        $this->localRatingRepository = $localRatingRepository;
    }

    public function index(LocalIndexFilter $localIndexFilter)
    {
        $locals = $this->localRepository->paginateFrontIndex($localIndexFilter);

        $formSearch = $this->form(LocalIndexSearchForm::class, ["model" => $localIndexFilter->getFilterValues()]);

        return view('front.locals.index', compact('locals', 'formSearch'));
    }

    public function show(LocalRatingShowFilter $localRatingShowFilter, int $id)
    {
        $local = $this->localRepository->findOrFail($id);

        $ratings = $this->localRatingRepository->paginateForLocal($local, $localRatingShowFilter);

        $formSearchRating = $this->form(LocalRatingShowSearchForm::class,["model" => $localRatingShowFilter->getFilterValues()]);

        return view('front.locals.show', compact('local','ratings','formSearchRating'));
    }
}

app/Http/Controllers/Front/LocalRatingController.php
<?php
/**
 * Created by PhpStorm.
 * User: Marcin-Komputer
 * Date: 14.12.2019
 * Time: 21:18
 */

namespace App\Http\Controllers\Front;


use App\Forms\Front\LocalRatingCreateForm;
use App\Http\Controllers\Controller;
use App\Repositories\LocalRatingRepository;
use App\Repositories\LocalRepository;
use App\Repositories\LocalVisitCodeRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class LocalRatingController extends Controller
{
    use FormBuilderTrait;

    protected $localRatingRepository;
    protected $localRepository;
    protected $localVisitCodeRepository;

    public function __construct(
        LocalRatingRepository $localRatingRepository,
        LocalRepository $localRepository,
        LocalVisitCodeRepository $localVisitCodeRepository
    )
    {
        $this->localRatingRepository = $localRatingRepository;
        $this->localRepository = $localRepository;
        $this->localVisitCodeRepository = $localVisitCodeRepository;
    }

    public function index(int $local_id)
    {
        $local = $this->localRepository->findOrFail($local_id);

        $items = $this->localRatingRepository->paginateForLocal($local);

        return view('front.locals_ratings.index',compare('local','items'));
    }

    public function create(Request $request)
    {
        $local_id = $request->session()->get('local_id');
        $code_id = $request->session()->get('code_id');

        $local = $this->localRepository->findOrFail($local_id);
        $visitCode = $this->localVisitCodeRepository->findOrFail($code_id);

        if($visitCode->local_id != $local->id)
            return redirect()->route('front.locals.visit_codes.showFormVisitCode')->with('error', trans('messages.locals_visit_codes.find_for_local.error'));

        if($visitCode->expired)
            return redirect()->route('front.locals.visit_codes.showFormVisitCode')->with('error', trans('messages.locals_visit_codes.expired.error'));

        $form = $this->form(LocalRatingCreateForm::class, [
            'method' => 'POST',
            'url' => route('front.ratings.store')
        ]);

        return view('front.locals_ratings.create',compact('local', 'form'));
    }

    public function store(Request $request)
    {
        $local_id = $request->session()->get('local_id');
        $code_id = $request->session()->get('code_id');

        $local = $this->localRepository->findOrFail($local_id);
        $visitCode = $this->localVisitCodeRepository->findOrFail($code_id);

        if($visitCode->local_id != $local->id)
            return redirect()->route('front.locals.visit_codes.showFormVisitCode')->with('error', trans('messages.locals_visit_codes.find_for_local.error'));

        if($visitCode->expired)
            return redirect()->route('front.locals.visit_codes.showFormVisitCode')->with('error', trans('messages.locals_visit_codes.expired.error'));


        $form = $this->form(LocalRatingCreateForm::class);

        if(!$form->isValid())
            return redirect()->back()->withInput()->withErrors($form->getErrors())->with('error', trans('messages.locals_ratings.store.error'));;

        $rating = $this->localRatingRepository->findOrNew();

        $rating->user_id = Auth::user()->id;
        $rating->local_id = $local_id;
        $rating->code_id = $code_id;

        $this->localRatingRepository->updateByData($rating,$form->getFieldValues());

        $this->localRatingRepository->store($rating);

        $visitCode->expired = 1;
        $this->localVisitCodeRepository->store($visitCode);

        return redirect()->route('front.locals.show', ['local_id' => $local->id])->with('success', trans('messages.locals_ratings.store.success'));
    }
}

app/Http/Controllers/Front/LocalVisitCodeController.php
<?php
/**
 * Created by PhpStorm.
 * User: Marcin-Komputer
 * Date: 14.12.2019
 * Time: 21:46
 */

namespace App\Http\Controllers\Front;


use App\Forms\Front\LocalVisitCodeForm;
use App\Http\Controllers\Controller;
use App\Models\LocalVisitCode;
use App\Repositories\LocalRepository;
use App\Repositories\LocalVisitCodeRepository;
use Illuminate\Auth\AuthManager;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilderTrait;
use Auth;

class LocalVisitCodeController extends Controller
{
    use FormBuilderTrait;

    protected $localVisitCodeRepository;
    protected $localRepository;

    public function __construct(
        LocalVisitCodeRepository $localVisitCodeRepository,
        LocalRepository $localRepository
    )
    {
        $this->localVisitCodeRepository = $localVisitCodeRepository;
        $this->localRepository = $localRepository;
    }

    public function showFormVisitCode()
    {
        if(!Auth::check())
            return redirect()->route('front.login.showLoginForm');

        $form = $this->form(LocalVisitCodeForm::class, [
            'method' => 'POST',
            'url' => route('front.visit_codes.choiceForm')
        ]);

        return view('front.locals_visit_codes.showFormVisitCode' ,compact('form'));
    }

    public function choiceForm(Request $request)
    {
        $form = $this->form(LocalVisitCodeForm::class);

        if(!$form->isValid())
            return redirect()->back()->withInput()->withErrors($form->getErrors());

        $code = $form->getFieldValues()['code'];

        $visitCodeItem = $this->localVisitCodeRepository->findCode($code);

        if(!$visitCodeItem)
            return redirect()->back()->with('error', trans('messages.locals_visit_codes.find_code.error'));

        $local = $this->localRepository->findOrFail($visitCodeItem->local_id);

        $request->session()->put('local_id', $local->id);
        $request->session()->put('code_id', $visitCodeItem->id);

        return view('front.locals_visit_codes.choiceForm', compact('local', 'visitCodeItem'));
    }
}

resources/views/front/locals/show.blade.php
@extends('front.commons.base.main')
@section('content')
    <div class="row">
        <div class="col-7">
            <div class="card">
                <div class="card-body">
                    <div class="images">
                        <img src="{{  $local->image_main ? '/storage/'.$local->image_main->thumbnail_image_path : '' }}"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-5">
            <div class="card">
                <div class="card-body">
                    <div class="basic-informations">
                        <div class="info">
                            <div class="name">
                                <h4>{{ $local->local_type->name }}</h4>
                                <h2><strong>{{ $local->name }}</strong></h2>
                            </div>
                            <div class="address">
                                <b>Adres:</b>
                                <div>
                                    {{ $local->address }}
                                </div>
                            </div>
                            <div class="local_opening_hours">
                                <b>Godziny otwarcia:</b>
                                <div class="nav-item dropdown">
                                    <div class="btn p-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{ (trans('days_of_week.days.'.date('N').'.shortPL')) .' | '. (isset($local->local_opening_hours) ? $local->local_opening_hours->getOpeningHoursForNumberDay(date('N')) : 'Godziny nieustawione') }}
                                    </div>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <table>
                                            <tbody>
                                            @foreach(array_keys(trans('days_of_week.days')) as $numberDay)
                                                <tr class="dropdown-item">
                                                    <td style="width: 50px">
                                                        {{ (trans('days_of_week.days.'.$numberDay.'.shortPL')) }}
                                                    </td>
                                                    <td>
                                                        {{ ' | '.(isset($local->local_opening_hours) ? $local->local_opening_hours->getOpeningHoursForNumberDay($numberDay) : 'Godziny nieustawione') }}
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="stats_info">
                            <div class="rating">
                                <i class="fas fa-star"></i> {{ $local->local_stats->rating }} ({{ $local->local_stats->count_rating }})
                            </div>
                            <div class="comments">
                                <i class="fas fa-comment"></i> {{ $local->local_stats->count_comments }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="information-content card">
            <div class="card-body">
                <ul class="nav mb-3 justify-content-center" id="pills-tab" role="tablist">
                    <li class="nav-item">
                        <a class="description nav-link active" id="pills-description-tab" data-toggle="pill" href="#pills-description" role="tab" aria-controls="pills-description" aria-selected="true">
                            <i class="fas fa-info"></i>
                            Opis
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="events nav-link" id="pills-events-tab" data-toggle="pill" href="#pills-events" role="tab" aria-controls="pills-events" aria-selected="true">
                            <i class="fas fa-glass-cheers"></i>
                            Wydarzenia
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="map nav-link" id="pills-map-tab" data-toggle="pill" href="#pills-map" role="tab" aria-controls="pills-map" aria-selected="false">
                            <i class="fas fa-map-marker-alt"></i>
                            Mapa
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="menu nav-link" id="pills-menu-tab" data-toggle="pill" href="#pills-menu" role="tab" aria-controls="pills-menu" aria-selected="false">
                            <i class="fas fa-utensils"></i>
                            Menu
                        </a>
                    </li>
                </ul>
                <div class="col-12 tab-content" id="pills-tabContent">
                    <div class="description tab-pane fade show active" id="pills-description" role="tabpanel" aria-labelledby="pills-description-tab">
                        Opis:
                        {{ $local->description }}
                    </div>
                    <div class="events tab-pane fade" id="pills-events" role="tabpanel" aria-labelledby="pills-events-tab">
                        Wydarzenia:
                    </div>
                    <div class="map tab-pane fade" id="pills-map" role="tabpanel" aria-labelledby="pills-map-tab">
                        <div id="myMap" data-longitude="{{ $local->longitude }}" data-latitude="{{ $local->latitude }}"></div>
                    </div>
                    <div class="menu tab-pane fade" id="pills-menu" role="tabpanel" aria-labelledby="pills-menu-tab">
                        <ul>
                            <li> Praesent in leo - 234 dolor.</li>
                            <li> Praesent in leo - 234 dolor.</li>
                            <li> Praesent in leo - 234 dolor.</li>
                            <li> Praesent in leo - 234 dolor.</li>
                            <li> Praesent in leo - 234 dolor.</li>
                            <li> Praesent in leo - 234 dolor.</li>
                            <li> Praesent in leo - 234 dolor.</li>
                            <li> Praesent in leo - 234 dolor.</li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>

    <div class="card comments_content">
        <div class="comments_header col-12">
            <div class="row">
                <div class="col-3 comments_title">
                    Opinie
                </div>
                <div class="col-9 filter_comments text-right">
                    <a id="headingOne" class="btn filters_btn" data-toggle="collapse" href="#collapseFilters" role="button" aria-expanded="false" aria-controls="collapseFilters"><i class="fas fa-filter"></i> Filtry</a>
                </div>
                <div id="collapseFilters" class="collapse">
                    <div class="card-body">
                        {!! form_start($formSearchRating) !!}
                        <div class="row">
                            <div class="col-md-3 col-sm-6 col-12">
                                {!! form_row($formSearchRating->rating_from) !!}
                            </div>
                            <div class="col-md-3 col-sm-6 col-12">
                                {!! form_row($formSearchRating->rating_to) !!}
                            </div>
                            <div class="col-md-3 col-sm-6 col-12">
                                {!! form_row($formSearchRating->created_from) !!}
                            </div>
                            <div class="col-md-3 col-sm-6 col-12">
                                {!! form_row($formSearchRating->created_to) !!}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3 col-sm-6 col-12">
                                {!! form_row($formSearchRating->submit) !!}
                            </div>
                        </div>
                        {!! form_start($formSearchRating) !!}
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="comments">
                @foreach($ratings as $rating)
                    <div class="comment">
                        <div class="row">
                            <div class="col-1 comment_author_image">
                                <img class="image" src="/images/pub.jpg"/>
                            </div>
                            <div class="col-11">
                                <div class="comment_author">
                                    {{ $rating->user->name }}
                                    <small>
                                        {{ $rating->created_at }}
                                    </small>
                                </div>
                                <div class="comment_rating">
                                    @for($i = 0; $i < $rating->rating; $i++)
                                        <i class="fas fa-star"></i>
                                    @endfor
                                </div>
                                <div class="comment_content">
                                    {{ $rating->comment }}
                                </div>
                                <div class="comment_buttons">
                                    <a class="btn" href="#"><i class="far fa-thumbs-up"></i> Lubię <strong>(342)</strong></a>
                                    <a class="btn" href="#"><i class="far fa-thumbs-down"></i> Nie lubię <strong>(57)</strong></a>
                                    <a class="btn" href="#"><i class="fas fa-quote-right"></i> Cytuj</a>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection